### ISSUE TITLE
Errors installing in Ubuntu 20.04

### ISSUE THREAD

**Issue by gbishop** [shaeinst/roshnivim#10]
I have installed nvim v0.7.0. 

When running your installer I see this error:

[lsp-installer] [ERROR 11:41:55]...ested URL returned error: 404 \n'[lsp-installer] [INFO  11:41:55]...name="sumneko_lua", success=false

Then it appears to be stalled. If I installed sumneko_lua manually, I don't get that error but it doesn't seem to make any progress and doesn't install other lsp's.

**Comment by AlixShahid** [comment]
can you please paste the full log of installer?
i think setup.py script need some works.
for now, you can install it manually
```bash
1. $ git clone https://github.com/shaeinst/roshnivim ~/.config/nvim
2. # then comment out line number 33 in ~/.config/nvim/lua/configs.lua flie  (--  cmd('colorscheme rvcs')
3. $ nvim -c PackerSync
4. # now uncomment   line number 33 in ~/.config/nvim/lua/configs.lua flie
5. # to install LSP, use PackerInstall <LSPname>. eg: :LspInstall clangd

```

i have exams. i will fix install script later


edit:
 followings dirs are required
```bash
~/.cache/nvim
~/.cache/nvim/swap
~/.cache/nvim/backedUP
~/.cache/nvim/undos
~/.cache/nvim/view
~/.cache/nvim/shada/shada

```

**Comment by AlixShahid** [comment]
@gbishop [setup.py](https://github.com/shaeinst/roshnivim/blob/main/setup.py) has been updated. 
``` bash
python <(curl -s https://raw.githubusercontent.com/shaeinst/roshnivim/main/setup.py)
```
would work fine

**Comment by gbishop** [comment]
Thanks. I'll try it out again when I get a chance.
