### ISSUE TITLE
regarding .config/nvim directory

### ISSUE THREAD

**Issue by p4nd4tz** [shaeinst/roshnivim#2]
Hey dude, 
Your whole project is awesome, but you are moving your whole directory to '.config/nvim' which make it as git directory.
Which is not good. Add something that will not make it as git.

**Comment by AlixShahid** [comment]
I make small changes almost every hour, and making it a git directory helps me test and commit without any extra step.


can you please tell me why?
>  which make it as git directory.
Which is not good. Add something that will not make it as git.

**Comment by p4nd4tz** [comment]
``` if [ "$current_dir" != "$nvim_conf_path" ]; then
  if [ ! -d "$nvim_conf_path" ]; then
	cd $current_dir
	cp ../roshnivim "$nvim_conf_path" -r ```

think about it again. we would not like to have '.config/nvim/' as git.You should add a code remove setup.sh, LICENSE, README.md from '.config/nvim' after coping.

**Comment by AlixShahid** [comment]
ok, this makes sense. i will do this soon

**Comment by AlixShahid** [comment]
@Abhishek416 i have converted ```setup.sh``` to ```setup.py```.
now you can install the roshnivim without keeping ```.git```, ```README.md```, ... by passing ```--delete 1``` as argument while running ```setup.py``` script

For Example:
```bash
python setup.py --delete 1
```
or,  single command to install clean roshnivim:
```bash
python <(curl -s https://raw.githubusercontent.com/shaeinst/roshnivim/main/setup.py) --delete 1
```
