### ISSUE TITLE
Solution for deleting blank line

### ISSUE THREAD

**Issue by voyeg3r** [shaeinst/roshnivim#22]
Just press uppercase J 
It will "delete" current line with no need of a function

**Comment by AlixShahid** [comment]
you mean join?
from `:h J`
>J                    Join [count] lines, with a minimum of two lines.
                        Remove the indent and insert up to two spaces (see
                        below).  Fails when on the last line of the buffer.
                        If [count] is too big it is reduced to the number of
                        lines available.

it's vim/neovim 's default behavior.
