### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by root-hatch** [shaeinst/roshnivim#30]
Hi,
I was looking for a contribution guide, but couldn't find it in the docs. Could you write one? It's hard to know what kind of help do you expect from the community, if any. Some kind of plan, or a roadmap would be nice :D

Also, [showcase page](https://abstract-ide.github.io/site/Showcase) is empty and there's information what are the plans for it.

Thank you for your hard work!

**Comment by AlixShahid** [comment]
actually i am very busy these days. Any help with open issues would be great. showcase page is for showing screenshots and videos of Abstract (like showing features)

**Comment by root-hatch** [comment]
Ok, thank you for the information.
I wish you a pleasant day, @shaeinst!
