### ISSUE TITLE
Neovim 0.9 filetype_to_parsername is deprecated

### ISSUE THREAD

**Issue by doctorfree** [shaeinst/roshnivim#31]
It appears that in Neovim 0.9 `filetype_to_parsername` is deprecated and should be replaced with `vim.treesitter.language.register`

This causes a warning when starting Abstract with v0.9 or later. I think the following modification to `lua/plugins/nvim-treesitter.lua` will accomplish the same thing without warning:

```lua
-- local parsername = parsers.filetype_to_parsername
-- parsername.htmldjango = 'html' -- enable html parser in htmldjango file
-- parsername.zsh = 'bash' -- enable bash parser in zsh file
   vim.treesitter.language.register('html', 'htmldjango')
   vim.treesitter.language.register('bash', 'zsh')
```

**Comment by doctorfree** [comment]
The full error message indicates not only is `filetype_to_parsername` deprecated in Neovim 0.9 but the setup script apparently calls a couple of unknown options, `open_on_setup` and `ignore_ft_on_setup`:

```
filetype_to_parsername is deprecated, please use 'vim.treesitter.language.register'
[NvimTree] unknown option: open_on_setup | [NvimTree] unknown option: ignore_ft_on_setup | see :help nvim-tree-setup for available configuration options
```

**Comment by AlixShahid** [comment]
@doctorfree I am very busy these days because of my exam. I will be free after 2 weeks

**Comment by doctorfree** [comment]
No rush. I maintain several projects and understand how these things go. Good luck on your exam!

**Comment by AlixShahid** [comment]
@doctorfree can you please test with the latest commit ?

**Comment by doctorfree** [comment]
@shaeinst with the latest commit these warnings are no longer shown when using Neovim 0.9. Good work, closing.
