### ISSUE TITLE
Run MasonUpdate when installing mason.nvim

### ISSUE THREAD

**Issue by doctorfree** [shaeinst/roshnivim#32]
I found I needed to run `:MasonUpdate` after installing the Abstract Neovim configuration. Otherwise I get a `:checkhealth` warning about the Mason registry. The `MasonUpdate` can be performed automatically during installation by using something like the following with the Packer plugin manager:

```lua
use {
    "williamboman/mason.nvim",
    run = ":MasonUpdate" -- :MasonUpdate updates registry contents
}
```
I'm not sure how Abstract implements the Packer plugin initialization. If Abstract can perform the MasonUpdate during install this will alleviate the need for the user to manually perform this task. Many Neovim configurations have this same issue.

**Comment by AlixShahid** [comment]
ok added the `run = ":MasonUpdate"` option. it's very hard for me to keep the eyes on every plugin. thanks.

**Comment by doctorfree** [comment]
I understand, these plugins rev so rapidly it's difficult to keep pace. I appreciate the prompt response on these minor issues. I tested with the latest commit and the Mason registry is now updated properly. Thanks!

I've added Abstract to the supported Neovim configurations in my [Lazyman Neovim Configuration Manager](https://github.com/doctorfree/nvim-lazyman).

Closing this issue
