### ISSUE TITLE
lspsaga and galaxyline maintained forks.

### ISSUE THREAD

**Issue by RayZ0rr** [shaeinst/roshnivim#5]
First of all, good repo :+1: 

There is a maintained fork of lspsaga:

https://github.com/tami5/lspsaga.nvim

I see you are using feline but nonetheless there's maintained fork of galaxyline :

https://github.com/NTBBloodbath/galaxyline.nvim

**Comment by AlixShahid** [comment]
thanks
> First of all, good repo 

actually I'm aware  of these  maintained forks. But i don't use lspsaga anymore.
>There is a maintained fork of lspsaga:
https://github.com/tami5/lspsaga.nvim

i have tested almost every lua based status line and after months, i made feline default.
>I see you are using feline but nonetheless there's maintained fork of galaxyline :
https://github.com/NTBBloodbath/galaxyline.nvim

**Comment by RayZ0rr** [comment]
Btw feline is now :- 
https://github.com/feline-nvim/feline.nvim
As famiu changed it to GitHub organisation or something like that
