### ISSUE TITLE
How to change color's theme?

### ISSUE THREAD

**Issue by luis-rodas** [shaeinst/roshnivim#6]
Hi, Guys
I'm using this amazing tool, but I'm facing a problem with current theme, I don't like the color, How can I change the colors? 
![Screen Shot 2022-01-17 at 8 41 48](https://user-images.githubusercontent.com/90215451/149808590-391bb47a-6557-43ef-84d3-f5932c966746.png)

**Comment by AlixShahid** [comment]
did you solve it?
